INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Barcelona LEBL', '2024-11-24', '14:55:00', 'IBE2335', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-24', '19:45:00', 'IBE2333', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-25', '09:30:00', 'IBE2331', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Barcelona LEBL', '2024-11-25', '16:45:00', 'IBE2335', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-25', '19:45:00', 'IBE2333', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-26', '09:30:00', 'IBE2331', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-26', '09:30:00', 'IBE2331', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-26', '19:45:00', 'IBE2333', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-27', '09:30:00', 'IBE2331', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Barcelona LEBL', '2024-11-27', '16:00:00', 'IBE2335', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-27', '19:45:00', 'IBE2333', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-28', '09:30:00', 'IBE2331', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Barcelona LEBL', '2024-11-28', '16:00:00', 'IBE2335', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-28', '19:45:00', 'IBE2333', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-29', '09:30:00', 'IBE2331', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Barcelona LEBL', '2024-11-29', '16:00:00', 'IBE2335', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-11-29', '19:45:00', 'IBE2333', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Barcelona LEBL', '2024-12-01', '14:55:00', 'IBE2335', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-12-01', '19:45:00', 'IBE2333', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-12-02', '09:35:00', 'IBE2331', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Barcelona LEBL', '2024-12-02', '16:45:00', 'IBE2335', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-12-02', '19:45:00', 'IBE2333', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-12-03', '09:30:00', 'IBE2331', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-12-03', '19:45:00', 'IBE2333', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-12-04', '09:30:00', 'IBE2331', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Barcelona LEBL', '2024-12-04', '16:00:00', 'IBE2335', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-12-04', '19:45:00', 'IBE2333', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-12-05', '09:30:00', 'IBE2331', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Barcelona LEBL', '2024-12-05', '16:00:00', 'IBE2335', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-12-05', '19:45:00', 'IBE2333', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-12-06', '09:30:00', 'IBE2331', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Barcelona LEBL', '2024-12-06', '16:00:00', 'IBE2335', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Salida', 'Iberia', 'Badajoz LEBZ', 'Madrid LEMD', '2024-12-06', '19:45:00', 'IBE2333', '1');