INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-11-24', '19:15:00', 'IBE2332', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Barcelona LEBL', 'Badajoz LEBZ', '2024-11-24', '14:25:00', 'IBE2334', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-11-25', '09:00:00', 'IBE2330', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Barcelona LEBL', 'Badajoz LEBZ', '2024-11-25', '14:25:00', 'IBE2334', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-11-25', '19:15:00', 'IBE2332', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-11-26', '09:00:00', 'IBE2330', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-11-26', '19:15:00', 'IBE2332', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-11-27', '09:00:00', 'IBE2330', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Barcelona LEBL', 'Badajoz LEBZ', '2024-11-27', '15:30:00', 'IBE2334', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-11-27', '19:15:00', 'IBE2332', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-11-28', '09:00:00', 'IBE2330', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Barcelona LEBL', 'Badajoz LEBZ', '2024-11-28', '15:30:00', 'IBE2334', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-11-28', '19:15:00', 'IBE2332', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-11-29', '09:00:00', 'IBE2330', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Barcelona LEBL', 'Badajoz LEBZ', '2024-11-29', '15:30:00', 'IBE2334', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-11-29', '19:15:00', 'IBE2332', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Barcelona LEBL', 'Badajoz LEBZ', '2024-12-01', '14:25:00', 'IBE2334', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-12-01', '19:15:00', 'IBE2332', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-12-02', '08:45:00', 'IBE2330', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Barcelona LEBL', 'Badajoz LEBZ', '2024-12-02', '16:15:00', 'IBE2334', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-12-02', '19:15:00', 'IBE2332', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-12-03', '09:00:00', 'IBE2330', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-12-03', '19:15:00', 'IBE2332', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-12-04', '09:00:00', 'IBE2330', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Barcelona LEBL', 'Badajoz LEBZ', '2024-12-04', '15:30:00', 'IBE2334', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-12-04', '19:15:00', 'IBE2332', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-12-05', '09:00:00', 'IBE2330', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Barcelona LEBL', 'Badajoz LEBZ', '2024-12-05', '15:30:00', 'IBE2334', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-12-05', '19:15:00', 'IBE2332', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-12-06', '09:00:00', 'IBE2330', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Barcelona LEBL', 'Badajoz LEBZ', '2024-12-06', '15:30:00', 'IBE2334', '1');
INSERT INTO `vuelos` (`id`, `tipo`, `company`, `dep`, `arr`, `fecha`, `hora`, `vuelo`, `terminal`) 
VALUES (NULL, 'Llegada', 'Iberia', 'Madrid LEMD', 'Badajoz LEBZ', '2024-12-06', '19:15:00', 'IBE2332', '1');